name: Notif on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
  
  runs-on: ubuntu-latest
  
  steps:
  - name: Send Push Notification
    uses: techulus/push-github-action@1.0.0
    env:
      API_KEY: ${{ a6ff21d5-9fff-43ed-85f8-185426ef9712 }}
      MESSAGE: "There is a new PR!"
